# Generated by Django 5.2.15 on 2026-08-26 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_name", models.CharField(max_length=255)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("metric_date", models.DateField()),
                (
                    "budget_utilization",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "outcome_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "inclusion_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sustainability_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "risk_index",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "compliance_index",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Metric",
                "verbose_name_plural": "Program Metrics",
                "ordering": ["-metric_date", "program_name"],
            },
        ),
    ]
