# Generated by Django 5.2.15 on 2026-07-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementplan',
            name='activity_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
