# Generated by Django 5.2.15 on 2026-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'Vehicle'), ('MOTORCYCLE', 'Motorcycle'), ('ICT', 'ICT Equipment'), ('FURNITURE', 'Furniture'), ('OFFICE', 'Office Equipment'), ('LAND', 'Land'), ('BUILDING', 'Building'), ('PLANT', 'Plant & Machinery')], max_length=50, null=True),
        ),
    ]
