# Generated by Django 5.2.15 on 2026-07-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0002_alter_procurementplan_activity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementplan',
            name='activity_name',
        ),
        migrations.AddField(
            model_name='requisition',
            name='activity_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
