# Generated by Django 5.2.15 on 2026-09-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other_category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'Vehicle'), ('MOTORCYCLE', 'Motorcycle'), ('ICT', 'ICT Equipment'), ('FURNITURE', 'Furniture'), ('OFFICE', 'Office Equipment'), ('LAND', 'Land'), ('BUILDING', 'Building'), ('PLANT', 'Plant & Machinery'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
