# Generated by Django 5.2.15 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0003_remove_procurementplan_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierspendreport',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_reports', to='procureapp.supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplierspendreport',
            constraint=models.UniqueConstraint(fields=('purchase_order',), name='unique_supplier_spend_report_per_purchase_order'),
        ),
    ]
