# Generated by Django 5.2.15 on 2026-08-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0004_alter_supplierspendreport_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierspendreport',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
