# Generated by Django 5.2.15 on 2026-07-06 22:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExitProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExitProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('clearance_form_sent', 'Clearance form sent'), ('clearance_form_submitted', 'Clearance form submitted'), ('handover_report_submitted', 'Handover report submitted'), ('exit_meeting_done', 'Exit meeting with HR'), ('hr_report_submitted_to_cmt', 'HR report submitted to CMT'), ('staff_dues_paid', 'Staff dues paid')], max_length=64)),
                ('step_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='exit_flow/')),
            ],
            options={
                'ordering': ['step_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
            options={
                'ordering': ('department__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('program_area', models.CharField(blank=True, choices=[('ARUA', 'Arua Program Area'), ('MOYO', 'Moyo Program Area')], max_length=255, null=True)),
                ('profile_type', models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Volunteer', 'Volunteer'), ('Intern', 'Intern'), ('Community Structure', 'Community Structure')], default='Staff', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('signature', models.FileField(blank=True, null=True, upload_to='Signature')),
                ('device_hash', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Exit', 'Exit'), ('Suspended', 'Suspended'), ('Probation', 'Probation')], db_index=True, default='Probation', max_length=20)),
                ('probation_starts', models.DateField(blank=True, null=True)),
                ('probation_ends', models.DateField(blank=True, null=True)),
                ('is_CMT', models.BooleanField(default=False)),
                ('can_review', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Profile',
                'ordering': ('first_name', 'last_name', 'username'),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
