# Generated by Django 5.2.15 on 2026-09-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_currency",
            field=models.CharField(
                choices=[
                    ("UGX", "Ugandan Shilling"),
                    ("KES", "Kenyan Shilling"),
                    ("NGN", "Nigerian Naira"),
                    ("SSP", "South Sudanese Pound"),
                    ("USD", "US Dollar"),
                ],
                default="UGX",
                help_text="Preferred currency for viewing monetary amounts across the system.",
                max_length=3,
            ),
        ),
    ]
