# Generated by Django 4.2.24 on 2026-09-15 13:52

from django.db import migrations, models
import django.db.models.deletion


def seed_program_areas(apps, schema_editor):
    # Preserves the two values the old hardcoded PROGRAM_AREA choices offered,
    # as a starting point now that program areas are a real, editable table.
    ProgramArea = apps.get_model("account", "ProgramArea")
    for name in ["Arua Program Area", "Moyo Program Area"]:
        ProgramArea.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_profile_display_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Program Area",
                "verbose_name_plural": "Program Areas",
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="program_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="account.programarea",
            ),
        ),
        migrations.RunPython(seed_program_areas, migrations.RunPython.noop),
    ]
