# Generated by Django 5.2.15 on 2026-09-21 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_edit_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="account",
        model="profile",
    )
    permission, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename="can_edit_records",
        defaults={
            "name": "Can edit, update, and delete records through temporary Edit access",
        },
    )
    group, _ = Group.objects.get_or_create(name="Edit")
    group.permissions.add(permission)


def remove_edit_permission(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.filter(app_label="account", model="profile").first()
    if not content_type:
        return
    permission = Permission.objects.filter(
        content_type=content_type,
        codename="can_edit_records",
    ).first()
    group = Group.objects.filter(name="Edit").first()
    if group and permission:
        group.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_programarea_alter_profile_program_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('first_name', 'last_name', 'username'), 'permissions': [('can_edit_records', 'Can edit, update, and delete records through temporary Edit access')], 'verbose_name': 'Profile'},
        ),
        migrations.CreateModel(
            name='EditAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_access_grants_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_access_grant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-granted_at',),
                'indexes': [models.Index(fields=['expires_at'], name='account_edi_expires_f890df_idx')],
            },
        ),
        migrations.RunPython(create_edit_group, remove_edit_permission),
    ]
