# Generated by Django 5.2.15 on 2026-08-26 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("department", models.CharField(blank=True, max_length=50, null=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at", "deadline"],
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("resume", models.FileField(upload_to="resumes/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Interview", "Interview"),
                            ("Rejected", "Rejected"),
                            ("Hired", "Hired"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "interview_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("interview_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_sent_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicants",
                        to="vacancy.jobopening",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecruitmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("justification", models.TextField()),
                ("hr_reviewed", models.BooleanField(default=False)),
                ("ed_approved", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("HRReviewed", "HR Reviewed"),
                            ("EDApproved", "ED Approved"),
                            ("Rejected", "Rejected"),
                            ("Published", "Published"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attach_file",
                    models.FileField(
                        blank=True, null=True, upload_to="recruitment_requests/"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=~models.Q(name="ED"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.unit",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.Case(
                        models.When(status="Pending", then=models.Value(0)),
                        default=models.Value(1),
                        output_field=models.IntegerField(),
                    ),
                    "-created_at",
                ],
            },
        ),
        migrations.AddField(
            model_name="jobopening",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_opening",
                to="vacancy.recruitmentrequest",
            ),
        ),
    ]
