# Generated by Django 5.2.15 on 2026-06-29 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='docs/')),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('resource_type', models.CharField(choices=[('presentation', 'Presentation'), ('report', 'Report'), ('success_story', 'Success Story')], max_length=25)),
                ('file', models.FileField(upload_to='resources/')),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('object_repr', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('quote_currency', models.CharField(default='UGX', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rate_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_manual', models.BooleanField(default=False)),
                ('is_fallback', models.BooleanField(default=False)),
                ('input_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_rates_input', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fetched_at',),
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', '-fetched_at'], name='core_curren_base_cu_c83d48_idx'), models.Index(fields=['base_currency', 'quote_currency', 'is_manual', '-rate_date'], name='core_curren_base_cu_769555_idx')],
            },
        ),
    ]
