# Generated by Django 5.2.15 on 2026-07-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coreprogram_location_project_projectbudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='head',
        ),
    ]
