# Generated by Django 5.2.15 on 2026-07-06 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0002_coreprogram_location_project_projectbudget'),
        ('procureapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finance_review', 'Finance Review'), ('assets_review', 'Assets Review'), ('operations_review', 'Operations Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('donor_code', models.CharField(max_length=100)),
                ('date_of_return', models.DateField()),
                ('description', models.TextField(help_text='Receipts and expenditures for: ......')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checked', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=50)),
                ('program_code', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.accountingform')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finance_review', 'Finance Review'), ('assets_review', 'Assets Review'), ('operations_review', 'Operations Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor_code', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('date', models.DateField()),
                ('reason_for_rejection', models.TextField(blank=True, null=True)),
                ('amount_in_words', models.CharField(blank=True, max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cash_requisitions/attachments/')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checked', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('procurement_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_requisitions', to='procureapp.requisition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminExpenseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finance_review', 'Finance Review'), ('assets_review', 'Assets Review'), ('operations_review', 'Operations Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_of_submission', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.TextField()),
                ('timeframe_from', models.DateField()),
                ('timeframe_to', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('objectives', models.TextField()),
                ('expected_outputs', models.TextField()),
                ('proposed_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_providers', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checked', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.department')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
                ('cash_req', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_concept', to='finance.cashrequisition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accountingform',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountings', to='finance.cashrequisition'),
        ),
        migrations.CreateModel(
            name='CashRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=50)),
                ('program_code', models.CharField(max_length=50)),
                ('particulars', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.cashrequisition')),
            ],
        ),
    ]
