# Generated by Django 5.2.15 on 2026-08-09 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('procureapp', '0004_alter_supplierspendreport_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrequisition',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_requisitions', to='procureapp.purchaseorder'),
        ),
    ]
