# Generated by Django 5.2.15 on 2026-07-06 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_coreprogram_location_project_projectbudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='E.g: 1.1.1', max_length=50, unique=True)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='E.g: 1.1', max_length=50, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='E.g: SO 1', max_length=50, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2, null=True)),
                ('status', models.CharField(blank=True, choices=[('Refugee', 'Refugee'), ('National', 'National')], default='National', max_length=20, null=True)),
                ('pwd', models.PositiveIntegerField(blank=True, null=True)),
                ('pwd_nationals', models.PositiveIntegerField(blank=True, default=0)),
                ('pwd_refugees', models.PositiveIntegerField(blank=True, default=0)),
                ('pwd_national_males', models.PositiveIntegerField(blank=True, default=0)),
                ('pwd_refugee_males', models.PositiveIntegerField(blank=True, default=0)),
                ('pwd_national_females', models.PositiveIntegerField(blank=True, default=0)),
                ('pwd_refugee_females', models.PositiveIntegerField(blank=True, default=0)),
                ('enterprise_type', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Retail', 'Retail'), ('Services', 'Services'), ('Other', 'Other')], default='Other', max_length=100, null=True)),
                ('no_of_enterprise', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_group_reached', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_group_members', models.PositiveIntegerField(blank=True, null=True)),
                ('no_male', models.PositiveIntegerField(blank=True, null=True)),
                ('no_female', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, help_text='Target', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('program_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coreprogram')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='monitoring.indicator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='monitoring.output'),
        ),
        migrations.AddField(
            model_name='output',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='monitoring.strategicobjective'),
        ),
    ]
