# Generated by Django 5.2.15 on 2026-08-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_indicator_slug_output_slug_strategicobjective_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
