# Generated by Django 5.2.15 on 2026-08-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_dataentry_slug_alter_indicator_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
