# Generated by Django 5.2.15 on 2026-08-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_dataentry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
