# Generated by Django 5.2.15 on 2026-08-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_dataentry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
