# Generated by Django 5.2.15 on 2026-06-29 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=100, unique=True)),
                ('date_of_entry', models.DateField()),
                ('category', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('MOTORCYCLE', 'Motorcycle'), ('ICT', 'ICT Equipment'), ('FURNITURE', 'Furniture'), ('OFFICE', 'Office Equipment'), ('LAND', 'Land'), ('BUILDING', 'Building'), ('PLANT', 'Plant & Machinery')], max_length=50)),
                ('description', models.TextField()),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('chasis_no', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(max_length=100)),
                ('mode_of_acquisition', models.CharField(choices=[('PROJECT FUNDED', 'Project Funded'), ('LOAN', 'Loan'), ('CAPITAL', 'Capital')], default='PROJECT FUNDED', max_length=100)),
                ('additions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('usage_years', models.PositiveIntegerField()),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation_accumulated', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('write_offs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_no'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maintenance_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='assetapp.asset')),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
