# Generated by Django 5.2.15 on 2026-09-15 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDisposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DECLARED', 'Declared'), ('UNDER_REVIEW', 'Under procurement review'), ('APPROVED', 'Approved for disposal'), ('DISPOSED', 'Disposed'), ('REJECTED', 'Rejected')], db_index=True, default='DECLARED', max_length=20)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('procurement_notes', models.TextField(blank=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_request', to='assetapp.asset')),
                ('declared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals_declared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-declared_at',),
            },
        ),
        migrations.CreateModel(
            name='WeeklyVehiclePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Use the Monday of the planning week')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_plans_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week_start',),
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_assignments', to='core.location')),
                ('vehicle', models.ForeignKey(limit_choices_to={'category': 'VEHICLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_assignments', to='assetapp.asset')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assetapp.weeklyvehicleplan')),
            ],
            options={
                'ordering': ('location', 'vehicle__asset_no'),
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyvehicleplan',
            constraint=models.UniqueConstraint(fields=('week_start',), name='unique_vehicle_plan_week'),
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.UniqueConstraint(fields=('plan', 'vehicle'), name='unique_vehicle_per_week'),
        ),
    ]
