# Generated by Django 5.2.15 on 2026-09-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0002_assetdisposalrequest_weeklyvehicleplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleassignment',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
