# Generated by Django 5.2.15 on 2026-09-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0003_alter_vehicleassignment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('VEHICLE', 'Vehicle'), ('MOTORCYCLE', 'Motorcycle'), ('ICT', 'ICT Equipment'), ('FURNITURE', 'Furniture'), ('OFFICE', 'Office Equipment'), ('LAND', 'Land'), ('BUILDING', 'Building'), ('PLANT', 'Plant & Machinery'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
