# Generated by Django 5.2.15 on 2026-08-26 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("risk_owner", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("code", models.CharField(blank=True, max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Impact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(unique=True)),
                ("descriptor", models.CharField(max_length=50)),
                ("definition", models.TextField()),
            ],
            options={
                "ordering": ["rating"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="impact_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Likelihood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(unique=True)),
                ("descriptor", models.CharField(max_length=50)),
                ("definition", models.TextField()),
            ],
            options={
                "ordering": ["rating"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="likelihood_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("risk_id", models.CharField(blank=True, max_length=10, unique=True)),
                ("event", models.TextField()),
                ("cause", models.TextField()),
                ("risk_score", models.PositiveSmallIntegerField(editable=False)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("SUBSTANTIAL", "Substantial"),
                            ("HIGH", "High"),
                            ("VERY HIGH", "Very High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("risk_owner", models.CharField(max_length=100)),
                ("risk_type", models.CharField(blank=True, max_length=100, null=True)),
                ("mitigation_plan", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Identified"),
                            ("ACCESSED", "Accessed"),
                            ("PLANNED", "Planned"),
                            ("IN PROGRESS", "In Progress"),
                            ("CONTROLLED", "Controlled"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="IDENTIFIED",
                        max_length=20,
                    ),
                ),
                ("date_identified", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("ai_used", models.BooleanField(default=False)),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("program", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "business_unit",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_fraud_related", models.BooleanField(default=False)),
                ("esg_area", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "continuity_dependency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "impact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="risk.impact",
                    ),
                ),
                (
                    "likelihood",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="risk.likelihood",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risks",
                        to="risk.riskcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessContinuityPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("critical_process", models.CharField(max_length=255)),
                ("recovery_owner", models.CharField(max_length=150)),
                (
                    "recovery_time_objective",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "recovery_point_objective",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("testing", "Testing"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("last_tested", models.DateField(blank=True, null=True)),
                ("next_test_due", models.DateField(blank=True, null=True)),
                ("continuity_actions", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="continuity_plans",
                        to="risk.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "next_test_due"],
            },
        ),
        migrations.CreateModel(
            name="RiskControl",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive"),
                            ("detective", "Detective"),
                            ("corrective", "Corrective"),
                            ("directive", "Directive"),
                        ],
                        default="preventive",
                        max_length=30,
                    ),
                ),
                ("owner", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "effectiveness",
                    models.CharField(
                        choices=[
                            ("strong", "Strong"),
                            ("adequate", "Adequate"),
                            ("needs_improvement", "Needs Improvement"),
                            ("weak", "Weak"),
                        ],
                        default="adequate",
                        max_length=30,
                    ),
                ),
                ("last_tested", models.DateField(blank=True, null=True)),
                ("next_test_due", models.DateField(blank=True, null=True)),
                ("evidence_reference", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controls",
                        to="risk.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RiskIncident",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("incident", "Incident"),
                            ("near_miss", "Near Miss"),
                            ("fraud", "Fraud"),
                            ("breach", "Control Breach"),
                            ("ethics", "Ethics Concern"),
                        ],
                        default="incident",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("reported_by", models.CharField(blank=True, max_length=150)),
                ("business_unit", models.CharField(blank=True, max_length=150)),
                ("event_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("triage", "Under Triage"),
                            ("investigating", "Investigating"),
                            ("contained", "Contained"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("SUBSTANTIAL", "Substantial"),
                            ("HIGH", "High"),
                            ("VERY HIGH", "Very High"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("immediate_action", models.TextField(blank=True)),
                ("investigation_notes", models.TextField(blank=True)),
                ("confidential", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="risk.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("owner", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("resources", models.TextField(blank=True, null=True)),
                (
                    "project_activity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("lessons_learned", models.TextField(blank=True, null=True)),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="risk.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "status"],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("multiplier", models.FloatField(default=1.0)),
                (
                    "risks",
                    models.ManyToManyField(related_name="scenarios", to="risk.risk"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdPartyRisk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("party_name", models.CharField(max_length=255)),
                ("service_category", models.CharField(max_length=150)),
                (
                    "risk_rating",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("SUBSTANTIAL", "Substantial"),
                            ("HIGH", "High"),
                            ("VERY HIGH", "Very High"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("compliance_status", models.CharField(blank=True, max_length=120)),
                ("contract_owner", models.CharField(blank=True, max_length=150)),
                ("due_diligence_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("conditional", "Conditional"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mitigation_requirements", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="third_party_exposures",
                        to="risk.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["party_name"],
            },
        ),
        migrations.CreateModel(
            name="WhistleblowerCase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_reference",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("allegation", models.CharField(max_length=255)),
                ("reporter_contact", models.CharField(blank=True, max_length=255)),
                ("anonymous", models.BooleanField(default=True)),
                ("reported_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("screening", "Screening"),
                            ("investigating", "Investigating"),
                            ("substantiated", "Substantiated"),
                            ("unsubstantiated", "Unsubstantiated"),
                            ("closed", "Closed"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("assigned_investigator", models.CharField(blank=True, max_length=150)),
                ("summary", models.TextField(blank=True)),
                ("outcome", models.TextField(blank=True)),
                ("donor_report_required", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whistleblower_cases",
                        to="risk.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KeyRiskIndicator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("metric_owner", models.CharField(max_length=150)),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "warning_threshold",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "breach_threshold",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("watch", "Watch"),
                            ("breached", "Breached"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("last_measured", models.DateField(blank=True, null=True)),
                ("response_plan", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kris",
                        to="risk.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "name"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="risk_keyris_status_e4595f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentalSocialRisk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("esg_area", models.CharField(max_length=120)),
                ("donor_standard", models.CharField(blank=True, max_length=150)),
                ("affected_stakeholders", models.TextField(blank=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("SUBSTANTIAL", "Substantial"),
                            ("HIGH", "High"),
                            ("VERY HIGH", "Very High"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("monitoring", "Monitoring"),
                            ("mitigating", "Mitigating"),
                            ("resolved", "Resolved"),
                        ],
                        default="identified",
                        max_length=20,
                    ),
                ),
                ("mitigation_plan", models.TextField(blank=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="esg_records",
                        to="risk.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "next_review_date"],
                "indexes": [
                    models.Index(
                        fields=["rating", "status"],
                        name="risk_enviro_rating_5cfa64_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(
                fields=["risk_level"], name="risk_risk_risk_le_cb4e7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(fields=["status"], name="risk_risk_status_10b721_idx"),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(
                fields=["category"], name="risk_risk_categor_7e2b9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskcontrol",
            index=models.Index(
                fields=["effectiveness"], name="risk_riskco_effecti_0eab5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskincident",
            index=models.Index(
                fields=["incident_type", "status"],
                name="risk_riskin_inciden_566ed8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskincident",
            index=models.Index(
                fields=["severity"], name="risk_riskin_severit_9c326b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thirdpartyrisk",
            index=models.Index(
                fields=["risk_rating", "status"], name="risk_thirdp_risk_ra_413584_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whistleblowercase",
            index=models.Index(
                fields=["status", "donor_report_required"],
                name="risk_whistl_status_1e8041_idx",
            ),
        ),
    ]
