# Generated by Django 5.2.15 on 2026-07-06 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('risk_owner', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(unique=True)),
                ('descriptor', models.CharField(max_length=50)),
                ('definition', models.TextField()),
            ],
            options={
                'ordering': ['rating'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='impact_range')],
            },
        ),
        migrations.CreateModel(
            name='Likelihood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(unique=True)),
                ('descriptor', models.CharField(max_length=50)),
                ('definition', models.TextField()),
            ],
            options={
                'ordering': ['rating'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='likelihood_range')],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('event', models.TextField()),
                ('cause', models.TextField()),
                ('risk_score', models.PositiveSmallIntegerField(editable=False)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('SUBSTANTIAL', 'Substantial'), ('HIGH', 'High'), ('VERY HIGH', 'Very High')], max_length=20)),
                ('risk_owner', models.CharField(max_length=100)),
                ('risk_type', models.CharField(blank=True, max_length=100, null=True)),
                ('mitigation_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('ACCESSED', 'Accessed'), ('PLANNED', 'Planned'), ('IN PROGRESS', 'In Progress'), ('CONTROLLED', 'Controlled'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='IDENTIFIED', max_length=20)),
                ('date_identified', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('ai_used', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk.impact')),
                ('likelihood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk.likelihood')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='risk.riskcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resources', models.TextField(blank=True, null=True)),
                ('project_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('lessons_learned', models.TextField(blank=True, null=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='risk.risk')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('multiplier', models.FloatField(default=1.0)),
                ('risks', models.ManyToManyField(related_name='scenarios', to='risk.risk')),
            ],
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['risk_level'], name='risk_risk_risk_le_cb4e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['status'], name='risk_risk_status_10b721_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['category'], name='risk_risk_categor_7e2b9b_idx'),
        ),
    ]
