# Generated by Django 5.2.15 on 2026-09-15 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliations_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('payment', 'Payment in cash book, not on statement'), ('receipt', 'Receipt on statement, not in cash book')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('payee', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.bankreconciliation')),
            ],
        ),
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Cash Book', max_length=200)),
                ('donor', models.CharField(blank=True, max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_books_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_books', to='core.project')),
            ],
            options={
                'ordering': ('-period_start', 'name'),
            },
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='cash_book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliation', to='finance.cashbook'),
        ),
        migrations.CreateModel(
            name='CashBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pv_number', models.CharField(blank=True, max_length=80)),
                ('budget_line', models.CharField(blank=True, max_length=80)),
                ('cheque_number', models.CharField(blank=True, max_length=80)),
                ('payee', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('receipt', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('comments', models.TextField(blank=True)),
                ('cash_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.cashbook')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_book_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FinanceBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('donor', models.CharField(blank=True, max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_budgets_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budgets', to='core.project')),
            ],
            options={
                'ordering': ('-period_start', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FinanceBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('activity', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frequency', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('justification', models.TextField(blank=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.financebudget')),
            ],
            options={
                'ordering': ('code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BudgetPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Use the first day of the reporting month')),
                ('funds_received', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_performance_created', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='finance.financebudget')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_records', to='finance.financebudgetline')),
            ],
            options={
                'ordering': ('-period', 'line__code'),
            },
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'code'), name='unique_budget_line_code'),
        ),
        migrations.AddConstraint(
            model_name='budgetperformance',
            constraint=models.UniqueConstraint(fields=('budget', 'line', 'period'), name='unique_budget_performance_period'),
        ),
    ]
