# Generated by Django 5.2.15 on 2026-09-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_seed_chart_of_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialtransaction",
            name="currency",
            field=models.CharField(
                default="UGX",
                help_text="The currency this transaction was actually recorded in.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="exchange_rate_used",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="UGX per 1 unit of `currency`, as used to compute `amount` at recording time.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="original_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount in the original `currency`, before conversion to UGX.",
                max_digits=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="UGX-equivalent amount, for cross-currency totals.",
                max_digits=16,
            ),
        ),
    ]
