# Generated by Django 4.2.24 on 2026-09-06 15:26

import core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_backfill_transaction_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingform",
            name="currency",
            field=models.CharField(
                default=core.services.get_base_currency,
                help_text="The currency this retirement was actually accounted in.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="accountingform",
            name="exchange_rate_used",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Base-currency units per 1 unit of `currency`, as used to convert item amounts at retirement time.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountingitem",
            name="original_amount_received",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount received in the parent form's own currency, before conversion to the base currency.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountingitem",
            name="original_amount_spent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount spent in the parent form's own currency, before conversion to the base currency.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminexpensenote",
            name="currency",
            field=models.CharField(
                default=core.services.get_base_currency,
                help_text="The currency this expense note was actually raised in.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="adminexpensenote",
            name="exchange_rate_used",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Base-currency units per 1 unit of `currency`, as used to convert proposed_budget at submission time.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminexpensenote",
            name="original_proposed_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Proposed budget in the note's own `currency`, before conversion to the base currency.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cashrequisition",
            name="currency",
            field=models.CharField(
                default=core.services.get_base_currency,
                help_text="The currency this requisition was actually raised in.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="cashrequisition",
            name="exchange_rate_used",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Base-currency units per 1 unit of `currency`, as used to convert item costs at submission time.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cashrequisitionitem",
            name="original_unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Unit cost in the parent requisition's own currency, before conversion to the base currency.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base-currency-equivalent amount, for cross-currency totals.",
                max_digits=16,
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="currency",
            field=models.CharField(
                default=core.services.get_base_currency,
                help_text="The currency this transaction was actually recorded in.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="original_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount in the original `currency`, before conversion to the base currency.",
                max_digits=16,
                null=True,
            ),
        ),
    ]
