# Generated by Django 5.2.15 on 2026-09-14 18:03

from decimal import Decimal
from django.db import migrations, models


def remap_transfer_and_capital_to_asset(apps, schema_editor):
    # The chart of accounts is expanding from 4 flat types (income, expense,
    # transfer, capital) to the standard 5-group structure (assets,
    # liabilities, equity, income, expenses). Neither "transfer" nor
    # "capital" survives as its own group — both were always fund/asset
    # movements, so they fold into "asset". Must run before the AlterField
    # below narrows the column's choices, or these rows would already be
    # invalid against the new choice list.
    FinancialCategory = apps.get_model("finance", "FinancialCategory")
    FinancialCategory.objects.filter(category_type__in=["transfer", "capital"]).update(category_type="asset")


def noop_reverse(apps, schema_editor):
    # Not reversible: "asset" rows that came from "transfer"/"capital" are
    # indistinguishable from ones that were always "asset" by this point.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_accountingform_currency_and_more"),
    ]

    operations = [
        migrations.RunPython(remap_transfer_and_capital_to_asset, noop_reverse),
        migrations.AddField(
            model_name="financialcategory",
            name="alt_code",
            field=models.CharField(
                blank=True,
                help_text="Optional secondary/legacy code for this account.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="financialcategory",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Balance carried in when this account was set up, in the organization's base currency.",
                max_digits=16,
            ),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("asset", "Assets"),
                    ("liability", "Liabilities"),
                    ("equity", "Equity"),
                    ("income", "Income"),
                    ("expense", "Expenses"),
                ],
                max_length=20,
            ),
        ),
    ]
