# Generated by Django 5.2.15 on 2026-09-14 18:21

import core.services
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


# Matches the numbering convention of the reference chart of accounts the
# UI was modeled on (1000 Assets, 2000 Liabilities, 3000 Equity, 4000
# Income, 5000 Expenses).
ROOT_GROUPS = [
    ("1000", "asset", "Assets"),
    ("2000", "liability", "Liabilities"),
    ("3000", "equity", "Equity"),
    ("4000", "income", "Income"),
    ("5000", "expense", "Expenses"),
]


def create_root_groups_and_reparent_accounts(apps, schema_editor):
    FinancialCategory = apps.get_model("finance", "FinancialCategory")
    base_currency = core.services.get_base_currency()

    roots_by_type = {}
    for code, category_type, name in ROOT_GROUPS:
        root, _ = FinancialCategory.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "category_type": category_type,
                "is_group": True,
                "currency": base_currency,
            },
        )
        roots_by_type[category_type] = root

    for category in FinancialCategory.objects.filter(parent__isnull=True, is_group=False):
        category.parent = roots_by_type[category.category_type]
        category.currency = base_currency
        category.save(update_fields=["parent", "currency"])


def noop_reverse(apps, schema_editor):
    # Not safely reversible — existing leaf accounts would be left with a
    # dangling parent reference to groups this reverse can't recreate on
    # forward-migrate again without risking duplicate root codes.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_expand_chart_of_accounts_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialcategory",
            name="currency",
            field=models.CharField(
                choices=[
                    ("UGX", "UGX"),
                    ("KES", "KES"),
                    ("NGN", "NGN"),
                    ("SSP", "SSP"),
                    ("USD", "USD"),
                ],
                default=core.services.get_base_currency,
                help_text="The currency this specific account is denominated in — opening/closing balance are shown in this currency.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="financialcategory",
            name="is_group",
            field=models.BooleanField(
                default=False,
                help_text="A group (folder) organizes other groups/accounts underneath it. Transactions can only post to non-group (leaf) accounts.",
            ),
        ),
        migrations.AddField(
            model_name="financialcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The group this account/sub-group sits under. Root groups (Assets, Liabilities, ...) leave this blank.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="finance.financialcategory",
            ),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Balance carried in when this account was set up, in the account's own currency.",
                max_digits=16,
            ),
        ),
        migrations.RunPython(create_root_groups_and_reparent_accounts, noop_reverse),
    ]
