# Generated by Django 4.2.24 on 2026-10-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_merge_finance_accounting_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                help_text="If set, this entry is a reversal that exactly offsets the linked entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_by",
                to="finance.journalentry",
            ),
        ),
    ]
