# Generated by Django 4.2.24 on 2026-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0015_alter_budgetperformance_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="financebudgetline",
            name="unique_budget_line_category",
        ),
        migrations.AddField(
            model_name="financebudgetline",
            name="frequency",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financebudgetline",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="financebudgetline",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financebudgetline",
            name="unit",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
