# Generated by Django 5.2.15 on 2026-07-06 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_submission', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('duty_station', models.CharField(blank=True, max_length=200)),
                ('years_in_org', models.CharField(blank=True, max_length=100)),
                ('job_description_score', models.IntegerField(blank=True, null=True)),
                ('job_description_interpretation', models.CharField(blank=True, max_length=50)),
                ('service_score', models.IntegerField(blank=True, null=True)),
                ('service_interpretation', models.CharField(blank=True, max_length=50)),
                ('significant_event', models.TextField(blank=True)),
                ('staff_opinion', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('capacity_gaps', models.TextField(blank=True, null=True)),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True, null=True)),
                ('cmt_comment', models.TextField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=200)),
                ('cmt_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_to_employee', 'Sent to Employee'), ('submitted_by_employee', 'Submitted by Employee'), ('reviewed_by_supervisor', 'Reviewed by Supervisor'), ('reviewed_by_hr', 'Reviewed by HR'), ('approved', 'Approved by CMT')], default='draft', max_length=50)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='appraisals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_appraisal', models.FileField(blank=True, null=True, upload_to='appraisals/filled/')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRapp.employee')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_appraisals', to='HRapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_to_staff', 'Sent to Staff'), ('submitted_by_staff', 'Submitted by Staff'), ('reviewed_by_hr', 'Reviewed by HR'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('improvement_areas', models.TextField(blank=True, help_text='Areas requiring improvement.')),
                ('improvement_actions', models.TextField(blank=True, help_text='Actions the employee will take.')),
                ('support_required', models.TextField(blank=True, help_text='Support expected from management.')),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('staff_commitment', models.TextField(blank=True, help_text="Employee's commitment statement.")),
                ('staff_signature', models.ImageField(blank=True, null=True, upload_to='pip/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pip', to='appraisals.appraisal')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pips', to='HRapp.employee')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_pips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
