# Generated by Django 5.2.15 on 2026-08-26 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("HRapp", "0001_initial"),
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="supervised_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="HRapp.employee",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HRapp.employee"
            ),
        ),
        migrations.AddField(
            model_name="educationhistory",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HRapp.employee"
            ),
        ),
        migrations.AddField(
            model_name="dependant",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HRapp.employee"
            ),
        ),
        migrations.AddField(
            model_name="bankdetail",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="HRapp.employee"
            ),
        ),
        migrations.AddField(
            model_name="employeeaddress",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HRapp.employee"
            ),
        ),
        migrations.AddField(
            model_name="employeecontact",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HRapp.employee"
            ),
        ),
        migrations.AddField(
            model_name="employeepersonalinfo",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="HRapp.employee"
            ),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="forumthread",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="HRapp.forumthread",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="ed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ed_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="hr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="HRapp.employee",
            ),
        ),
        migrations.AddField(
            model_name="leavedocument",
            name="leave",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="HRapp.leave",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HRapp.leavetype"
            ),
        ),
        migrations.AddField(
            model_name="orientationplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_orientation_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orientationplan",
            name="staff",
            field=models.OneToOneField(
                limit_choices_to=models.Q(status="Probation"),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orientation_plan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orientationsession",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="HRapp.orientationplan",
            ),
        ),
        migrations.AddField(
            model_name="orientationsession",
            name="scheduled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_orientation_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orientationsession",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orientation_sessions",
                to="account.unit",
            ),
        ),
        migrations.AddField(
            model_name="situationreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sitrep_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="special_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="HRapp.specialleavetype",
            ),
        ),
        migrations.AddField(
            model_name="staffdevice",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=~models.Q(department__name="ED"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HRapp.employee"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=~models.Q(id=models.F("supervised_by")),
                name="prevent_self_supervision",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orientationsession",
            unique_together={("plan", "unit")},
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["employee", "leave_type", "status", "start_date"],
                name="HRapp_leave_employe_4423c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["status", "start_date"], name="HRapp_leave_status_475559_idx"
            ),
        ),
    ]
