# Generated by Django 4.2.24 on 2026-08-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HRapp", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employee",
            name="prevent_self_supervision",
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=models.Q(("id", models.F("supervised_by")), _negated=True),
                name="employee_prevent_self_supervision",
            ),
        ),
        migrations.AddConstraint(
            model_name="leave",
            constraint=models.CheckConstraint(
                check=models.Q(("start_date__lte", models.F("end_date"))),
                name="leave_start_date_before_end_date",
            ),
        ),
    ]
