# Generated by Django 5.2.15 on 2026-06-29 15:07

import com_app.communication.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CORE', 'Core'), ('CROSS', 'Cross-cutting')], default='CORE', max_length=10)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='presentations/', validators=[com_app.communication.models.validate_pptx_file])),
                ('program_area', models.CharField(blank=True, choices=[('ARUA', 'Arua Program Area'), ('MOYO', 'Moyo Program Area')], max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('received', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/', validators=[com_app.communication.models.validate_word_file])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('report_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUAL', 'Biannual'), ('ANNUAL', 'Annual')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('received', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned')], default='SUBMITTED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('focus_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.focusarea')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_done', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communication.reportcomment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communication.report')),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Skills Development', max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='communication.focusarea')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.subgroup'),
        ),
    ]
